log_level                :info
log_location             STDOUT
node_name                'root'
client_key               '/root/chef-repo/.chef/your-root.pem'
validation_client_name   'chef-validator'
validation_key           '/root/chef-repo/.chef/your-chef-validator.pem'
chef_server_url          'https://your-chef-server-fqdn'
syntax_check_cache_path  '/root/chef-repo/.chef/syntax_check_cache'
cookbook_path            '/root/chef-repo/cookbooks'
